Repository CA-G12/To-Do-App-Yazeed-Ibtisam, pull requests merged in 2022-08, with the labels that each got.

#2 Added file structure
  .env.example
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/css/main.css
  public/index.html
  public/js/script.js
  src/controllers/categories/crud.js
  src/controllers/categories/query.js
  src/controllers/index.js
  src/controllers/tasks/crud.js
  src/controllers/tasks/query.js
  src/database/config/build.js
  src/database/queries/categories/crud.js
  src/database/queries/categories/index.js
  src/database/queries/categories/query.js
  src/database/queries/tasks/crud.js
  src/database/queries/tasks/index.js
  src/database/queries/tasks/query.js
  src/routes/categories.js
  src/routes/index.js
  src/routes/tasks.js
Labels: Done

#4 Finished setting up express and server and create database build files
  src/app.js
  src/database/config/build.sql
  src/database/config/connection.js
  src/database/config/insert.sql
  src/index.js
Labels: Awaiting review

#9 changes on controllers and queries and routes
  public/js/dom_utils.js
  public/js/script.js
  src/app.js
  src/controllers/index.js
  src/controllers/tasks/query.js
  src/database/config/build.sql
  src/database/config/connection.js
  src/database/config/insert.sql
  src/database/queries/tasks/crud.js
  src/database/queries/tasks/index.js
  src/database/queries/tasks/query.js
  src/routes/index.js
  src/routes/tasks.js
Labels: Done

#11 Created queries for database categories
  README.md
  public/css/main.css
  public/index.html
  public/index2.html
  public/js/modal.js
  public/js/tasks_view.js
  src/app.js
  src/controllers/categories/crud.js
  src/controllers/categories/query.js
  src/controllers/index.js
  src/database/queries/categories/crud.js
  src/database/queries/categories/index.js
  src/database/queries/categories/query.js
  src/routes/categories.js
  src/routes/index.js
Labels: Awaiting review

#14 finished crud function for task
  public/css/main.css
  public/js/modal.js
  public/js/script.js
  src/app.js
  src/controllers/categories/query.js
  src/controllers/index.js
  src/controllers/tasks/crud.js
  src/controllers/tasks/query.js
  src/database/queries/tasks/crud.js
  src/database/queries/tasks/index.js
  src/database/queries/tasks/query.js
  src/routes/categories.js
  src/routes/tasks.js
Labels: waiting review

#16 Completed function for adding and deleting tasks
  public/css/main.css
  public/index.html
  public/js/modal.js
  public/js/script.js
  src/controllers/categories/crud.js
  src/controllers/tasks/crud.js
  src/database/config/connection.js
Labels: waiting review

#17 Edit database
  README.md
  public/category.html
  public/css/main.css
  public/index.html
  public/js/dom_utils.js
  public/js/modal.js
  public/js/script.js
  src/controllers/tasks/crud.js
  src/database/config/build.sql
  src/database/config/insert.sql
  src/database/queries/tasks/query.js
Labels: Done

#18 Final changes
  README.md
  images/Project.PNG
  images/drawSQL-export-2022-08-24_10_10.png
  public/index.html
  public/js/modal.js
  public/js/script.js
  src/controllers/categories/query.js
  src/controllers/tasks/crud.js
  src/controllers/tasks/query.js
  src/database/queries/tasks/crud.js
  src/database/queries/tasks/query.js
Labels: Done
